AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - gemfiles/*
    - bin/*

Style/AccessorGrouping:
  EnforcedStyle: separated

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

# Disable predicate method enforcement for files where it produces false
# positives. It's use of boolean return values alone to determine if a method
# is a predicate method is not reliable enough.
Naming/PredicateMethod:
  Exclude:
    - "lib/authie/controller_delegate.rb"
    - "lib/authie/session.rb"
    - "lib/authie/session_model.rb"
